# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap

# Site settings
title: "rcher"
title2: "Hi, I'm Mayank!"
description: > # this means to ignore newlines until "email:"
   What's the deal with domain <span style="color: #cccccc">rcher</span> and <span style="color: #cccccc">blue ring</span> above?
description2: > # this means to ignore newlines until "email:"
  This space is meant to be a blog-styled thought-dump. I'll be writing about everything intriguing I've come across in my life, from meaningful movie dialogues to cool YouTube discoveries.

email: mayanksingh2298@gmail.com
#blog logo
logo: "/assets/images/blogging.png"
# blog cover
cover: "/assets/images/gow.jpg"

name: 'Mayank'
author: 'Mayank'
author_image: "/assets/images/blogging.png"

paginate:	5

url: "http://rcher.me" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@_iostreamer_'

#fill in disqus shortname to use disqus
disqus: io-streamer

# social icons and sharing options
social:
  - icon:	github
    url:	https://github.com/mayanksingh2298/
    desc: Fork me on github
    share_url: 
    share_title: 
    share_link: 
  - icon:	instagram
    url:	https://www.instagram.com/notyourdailymayank/
    desc: Follow me on instagram
    share_url: 
    share_title: 
    share_link:
  - icon:	linkedin
    url:	https://www.linkedin.com/in/mayank-singh-chauhan/
    desc: Connect with me on linkedin
    share_url: 
    share_title: 
    share_link: 